runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /gcode.php
  script: gcode.php

- url: /cal.php
  script: cal.php
  
- url: /
  static_files: index.html
  upload: index.html
   
- url: /
  static_files: cal.html
  upload: cal.html